apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: lvm-exporter
spec:
  groups:
  - name: lvm-exporter.rules
    rules:
    - alert: VolumeGroupAlmostFull
      annotations:
        description: 'LVM volume group {{ $labels.vg_name }} on node {{ $labels.node }} has only {{ $value}}% space left'
        summary: 'LVM volume group {{ $labels.vg_name }} on node {{ $labels.node }} has less than 10% space left'
      expr: 100*lvm_vg_free_bytes/lvm_vg_total_size_bytes < 10
      for: 15m
      labels:
        severity: critical
