apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: lvm-exporter
    release: prometheus
  name: lvm-exporter
  namespace: csi-lvm
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - csi-lvm
  selector:
    matchLabels:
      app: lvm-exporter
